import ctypes
from ctypes import c_void_p, c_char_p, c_uint32, c_uint16, c_uint64, c_int, c_bool, POINTER, Structure, CFUNCTYPE


class CONTEXT(Structure):
    _fields_ = [
        ("P1Home", c_uint64),
        ("P2Home", c_uint64),
        ("P3Home", c_uint64),
        ("P4Home", c_uint64),
        ("P5Home", c_uint64),
        ("P6Home", c_uint64),
        ("ContextFlags", c_uint32),
        ("MxCsr", c_uint32),
        ("SegCs", c_uint16),
        ("SegDs", c_uint16),
        ("SegEs", c_uint16),
        ("SegFs", c_uint16),
        ("SegGs", c_uint16),
        ("SegSs", c_uint16),
        ("EFlags", c_uint32),
        ("Dr0", c_uint64),
        ("Dr1", c_uint64),
        ("Dr2", c_uint64),
        ("Dr3", c_uint64),
        ("Dr6", c_uint64),
        ("Dr7", c_uint64),
        ("Rax", c_uint64),
        ("Rcx", c_uint64),
        ("Rdx", c_uint64),
        ("Rbx", c_uint64),
        ("Rsp", c_uint64),
        ("Rbp", c_uint64),
        ("Rsi", c_uint64),
        ("Rdi", c_uint64),
        ("R8", c_uint64),
        ("R9", c_uint64),
        ("R10", c_uint64),
        ("R11", c_uint64),
        ("R12", c_uint64),
        ("R13", c_uint64),
        ("R14", c_uint64),
        ("R15", c_uint64),
        ("Rip", c_uint64),
    ]

class DebugCAPI(Structure):
    _fields_ = [
        ("setBP", CFUNCTYPE(c_bool, c_uint64)),
        ("delBP", CFUNCTYPE(None, c_uint64)),
        ("getBpList", CFUNCTYPE(c_void_p)),
        ("setHwBP", CFUNCTYPE(c_bool, c_uint64, c_char_p, c_int)),
        ("delHwBP", CFUNCTYPE(c_bool, c_uint64)),
        ("getHwBpList", CFUNCTYPE(c_void_p)),
        ("step", CFUNCTYPE(None)),
        ("stepOver", CFUNCTYPE(None)),
        ("stepOut", CFUNCTYPE(None)),
        ("run", CFUNCTYPE(None)),
        ("stop", CFUNCTYPE(None)),
        ("getCont", CFUNCTYPE(POINTER(CONTEXT))),
        ("chgReg", CFUNCTYPE(c_bool, c_char_p, c_uint64)),
        ("memDump", CFUNCTYPE(c_uint64, c_uint64, c_void_p, c_uint64)),
        ("memEdit", CFUNCTYPE(c_bool, c_uint64, c_void_p, c_uint64)),
        ("getMods", CFUNCTYPE(c_void_p)),
        ("getThreads", CFUNCTYPE(c_void_p)),
    ]